config/routes.rb
Rails.application.routes.draw do
  root   "static_pages#home"
  get    "/help",    to: "static_pages#help"
  get    "/about",   to: "static_pages#about"
  get    "/contact", to: "static_pages#contact"
  get    "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers, :chat
    end
  end
  get "votes/create"
  get "votes/destroy"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # resources :microposts do
  #   member do
  #     patch "like", to: "microposts#like"
  #   end
  #   resources :comments
  #   resource :emote, only: :show
  # end
  resources :microposts do
    member do
      patch "like", to: "microposts#like"
    end
    resources :comments
    resource :emote do
      get :count_emoji
    end
  end
  resources :comments do
    resource :emote, only: :show
  end
  resources :likes, only: [:create, :destroy]

  resources :rooms do
    resources :messages
  end
  resources :relationships, only: [:create, :destroy]
  get "/microposts", to: "static_pages#home"
  # login devise
  # devise_for :users ,
  #            controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier
  has_many :emotes, dependent: :destroy
  belongs_to :user
  belongs_to :micropost
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :comments, foreign_key: "post_parent_id", dependent: :destroy
  validates :body, presence: true, allow_blank: false
  after_create_commit do
    if parent.present?
      broadcast_append_to [micropost, :comments], target: "#{dom_id(micropost, parent.id)}_comments"
    else
      broadcast_append_to [micropost, :comments], target: "#{dom_id(micropost)}_comments"
    end
  end

  after_destroy_commit do
    broadcast_remove_to self
  end

  after_update_commit do
    broadcast_replace_to self
  end

  def emotes_size key
    self.emotes.count { |e| e.emoji == key }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::RecordIdentifier
  include CommentsHelper
  before_action :set_current_user
  before_action :authenticate_user!
  load_and_authorize_resource :micropost
  load_and_authorize_resource :comment

  def new
    @comment = Comment.new
    @parent = Comment.find_by(id: params[:post_parent_id])
  end

  def edit
  end

  def create
    @comment = @micropost.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.turbo_stream { }
        format.html { redirect_to root_url, locals: { comment: Comment.new }}
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(dom_id_for_records(@micropost, @comment),
                                                    partial: "comments/form",
                                                    locals: { micropost: @micropost, comment: @comment })
        }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated."}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_parent_id, :micropost, :user)
  end

  def set_current_user
    @current_user = current_user
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def dom_id_for_records(*records, prefix: nil)
    records.map { |record| dom_id(record, prefix) }.join("_")
  end
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>
<%= turbo_frame_tag comment do %>
  <div id="comment-<%= comment.id %>" class="comment">
    <%= link_to gravatar_for(comment.user, size: 25), comment.user %>
    <span class="user"><%= link_to comment.user.name, comment.user %></span>
    <br/>
    <span class="content">
      <%= comment.body %>
    </span>
    <span class="action">
      <% Emoji.all_emoji.each do |emoji| %>
        <% size = comment.emotes_size(emoji[:key]) %>
        <%= link_to comment_emote_path(comment, emote: emoji[:key]), class: "emoji #{size.zero? ? 'emoji-gray' : ''}" do %>
          <%= image_tag File.join('emojis', emoji[:key]), size: '25x25', title: emoji[:text] %>
          <%= content_tag :span, size, class: 'count' %>
        <% end %>
      <% end %>
      <% if @current_user == comment.user %>
        <%= link_to "Edit", edit_comment_path(comment) %>
      <% end %>
      <% if @current_user == comment.user || @current_user == comment.micropost.user %>
        <%= link_to "Delete", comment, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </span>
  </div>
  <%= turbo_frame_tag "new_comment" do %>
    <span class="timestamp">
      <%= link_to "Reply", new_micropost_comment_path(comment.micropost, post_parent_id: comment.id) %>
      <%= time_ago_in_words(comment.created_at) %> ago.
    </span>
  <% end %>
  <div class="sub_comment">
    <%= tag.div id: "#{dom_id(comment.micropost, comment.id)}_comments" do %>
      <%= render comment.comments if comment.comments.any? %>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<% model = [local_assigns[:micropost], @comment].compact %>
<%= form_with model: model, id: dom_id_for_records(*model), data: { controller: "turbo", action: "turbo:submit-end->reset-form#reset" } do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger">
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this micropost from being saved:</h2>
        <ul>
          <% @comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <% if @parent.present? %>
    <input type="hidden" name="comment[post_parent_id]" value="<%= @parent.id %>">
  <% end %>
  <%= link_to gravatar_for(current_user, size: 25), current_user %>
  <span class="user"><%= link_to current_user.name, current_user %></span>
  <%= f.text_field :body, placeholder: "Add a comment...", class: "text-field" %>
  <%= f.submit "Comment", class: "btn btn-info", style: "width: 120px" %>
  <hr>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render 'form', comment: @comment %>
<% end %>

app/views/comments/edit.js.erb
$('#show').html("<%=escape_javascript render(:partial => 'form') %>");

app/views/comments/new.html.erb
<%= turbo_frame_tag "new_comment", target: "_top" do %>
  <%= render 'form', micropost: @micropost, comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>