config/routes.rb
Rails.application.routes.draw do
  root   "static_pages#home"
  get    "/help",    to: "static_pages#help"
  get    "/about",   to: "static_pages#about"
  get    "/contact", to: "static_pages#contact"
  get    "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers, :chat
    end
  end
  get "votes/create"
  get "votes/destroy"
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  # resources :microposts do
  #   member do
  #     patch "like", to: "microposts#like"
  #   end
  #   resources :comments
  #   resource :emote, only: :show
  # end
  resources :microposts do
    member do
      patch "like", to: "microposts#like"
    end
    resources :comments
    resource :emote do
      get :count_emoji
    end
  end
  resources :comments do
    resource :emote, only: :show
  end
  resources :likes, only: [:create, :destroy]

  resources :rooms do
    resources :messages
  end
  resources :relationships, only: [:create, :destroy]
  get "/microposts", to: "static_pages#home"
  # login devise
  # devise_for :users ,
  #            controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  CSV_ATTRIBUTES = %w(content created_at).freeze
  acts_as_votable
  has_many :comments, dependent: :destroy
  has_many :emotes, dependent: :destroy
  has_many :likes
  belongs_to       :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image,   content_type: { in: %w(image/jpeg image/gif image/png),
                                      message: "must be a valid image format" },
                      size: { less_than: 5.megabytes,
                              message:   "should be less than 5MB" }

  # Returns a resized image for display.
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

  def emotes_size key
    self.emotes.count { |e| e.emoji == key }
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  load_and_authorize_resource :micropost
  load_and_authorize_resource :comment

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render "static_pages/home"
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    if request.referer.nil? || request.referer == microposts_url
      redirect_to root_url
    else
      redirect_to request.referer
    end
  end

  def like
    @micropost = Micropost.find(params[:id])
    if current_user.voted_up_on? @micropost
      @micropost.downvote_by current_user
    elsif current_user.voted_down_on? @micropost
      @micropost.upvote_by current_user
    else #not voted
      @micropost.upvote_by current_user
    end
    respond_to do |format|
      format.js
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    respond_to do |format|
      format.js
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    respond_to do |format|
      format.js
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_like.html.erb
<%= link_to "Like", likes_micropost_path(micropost), method: :put, remote: true %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.display_image if micropost.image.attached? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                  data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>
<% if current_user %>
  <%= content_tag "div", id: "like-link-#{micropost.id}" do %>
    <%= render 'likes/like_link', micropost: micropost %>
  <% end %>
<% end %>
<%= turbo_stream_from micropost, :comments %>
<%= tag.div id: "#{dom_id(micropost)}_comments" do %>
  <%= render micropost.comments.where(post_parent_id: nil) %>
<% end %>
</br>
<%= turbo_frame_tag "new_comment", src: new_micropost_comment_path(micropost), target: "_top" %>

app/views/microposts/_unlike.html.erb
<%= link_to "Unlike", likes_micropost_path(micropost), method: :put, remote: true %>

app/views/microposts/_vote.html.erb
<% if current_user.liked? micropost %>
  <%= render 'microposts/unlike',micropost: micropost%>
<% else %>
  <%= render 'microposts/like', micropost: micropost%>
<% end %>

app/views/microposts/vote.js.erb
<% if current_user.liked? @micropost %>
  $('#vote-micropost-<%= @micropost.id %>').html('<%= j render("microposts/unlike",micropost: @micropost)%>');
<% else %>
  $('#vote-micropost-<%= @micropost.id %>').html('<%= j render("microposts/like", micropost: @micropost) %>');
<% end %>